import { useChurch } from "@/components/ChurchLayout";
import { AdaptiveFormDialogBody, AdaptiveFormDialogContent, AdaptiveFormDialogFooter, adaptiveFormDialogHeaderClassName } from "@/components/AdaptiveFormDialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, GraduationCap, Lock, Play, Save } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

type StudentItem = { lesson: { id: number; title: string; summary?: string | null; content?: string | null; lessonDate?: string | Date | null; position: number; status: string }; progress?: { status: string; reflection?: string | null; releasedAt?: string | Date | null } | null; available: boolean };

export default function EscolaLideresAluno() {
  const { churchId } = useChurch();
  const utils = trpc.useUtils();
  const [selected, setSelected] = useState<StudentItem | null>(null);
  const [reflection, setReflection] = useState("");
  const { data: paths = [], isLoading, isError } = trpc.escolaLideres.studentPath.useQuery({ churchId: churchId! }, { enabled: Boolean(churchId), retry: false });
  const startLesson = trpc.escolaLideres.startStudentLesson.useMutation({ onSuccess: () => utils.escolaLideres.studentPath.invalidate(), onError: (error) => toast.error(error.message) });
  const completeLesson = trpc.escolaLideres.completeStudentLesson.useMutation({ onSuccess: async () => { toast.success("Aula concluída. Aguarde a revisão presencial do professor."); setSelected(null); await utils.escolaLideres.studentPath.invalidate(); }, onError: (error) => toast.error(error.message) });

  if (!churchId || isLoading) return <div className="p-4 sm:p-6"><div className="h-64 animate-pulse rounded-2xl bg-muted/30" /></div>;
  if (isError) return <div className="mx-auto max-w-xl p-6"><Card><CardContent className="p-8 text-center"><p className="font-semibold text-navy">Não foi possível carregar sua trilha.</p><p className="mt-2 text-sm text-muted-foreground">Confirme se sua conta está vinculada a uma Pessoa da igreja.</p></CardContent></Card></div>;
  const path = paths[0];
  const items = (path?.lessons ?? []) as StudentItem[];
  const completed = items.filter((item) => item.progress?.status === "concluida").length;
  const openLesson = (item: StudentItem) => { if (!item.available) return; setSelected(item); setReflection(item.progress?.reflection ?? ""); startLesson.mutate({ churchId, enrollmentId: path.enrollment.id, lessonId: item.lesson.id }); };

  return <div className="space-y-5 p-4 sm:p-6"><header className="flex items-start gap-3"><div className="rounded-2xl bg-[#1e3a5f] p-3 text-white"><GraduationCap className="h-6 w-6" /></div><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#c9a84c]">Escola de Líderes</p><h1 className="font-display text-2xl text-[#1e3a5f]">Minha formação</h1><p className="mt-1 text-sm text-muted-foreground">Estude no seu ritmo e participe da revisão presencial com o professor.</p></div></header>
    {!path ? <Card className="border-dashed"><CardContent className="p-10 text-center"><GraduationCap className="mx-auto h-10 w-10 text-muted-foreground" /><p className="mt-3 font-semibold text-navy">Sua matrícula ainda não está disponível</p><p className="mt-1 text-sm text-muted-foreground">Quando a liderança registrar sua matrícula, sua trilha aparecerá aqui.</p></CardContent></Card> : <Card className="overflow-hidden border-[#c9a84c]/25"><CardHeader className="bg-[linear-gradient(135deg,#fdfaf1_0%,#ffffff_55%,#f7f1e2_100%)]"><CardTitle className="text-[#1e3a5f]">{path.class.name}</CardTitle><p className="text-sm font-normal text-muted-foreground">{completed} de {items.length} aulas concluídas</p><div className="h-2 overflow-hidden rounded-full bg-[#1e3a5f]/10"><div className="h-full rounded-full bg-[#c9a84c]" style={{ width: `${items.length ? Math.round((completed / items.length) * 100) : 0}%` }} /></div></CardHeader><CardContent className="space-y-3 p-4 sm:p-6">{items.length ? items.map((item, index) => { const done = item.progress?.status === "concluida"; return <div key={item.lesson.id} className={`rounded-xl border p-3 ${item.available ? "bg-background" : "bg-muted/30"}`}><div className="flex items-start gap-3"><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-full ${done ? "bg-emerald-100 text-emerald-700" : item.available ? "bg-[#c9a84c]/20 text-[#1e3a5f]" : "bg-muted text-muted-foreground"}`}>{done ? <CheckCircle2 className="h-4 w-4" /> : item.available ? index + 1 : <Lock className="h-4 w-4" />}</span><div className="min-w-0 flex-1"><p className="text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">Aula {index + 1}</p><p className="font-semibold text-[#1e3a5f]">{item.lesson.title}</p>{item.lesson.summary ? <p className="mt-1 line-clamp-2 text-xs text-muted-foreground">{item.lesson.summary}</p> : null}<Badge className="mt-2" variant={done ? "default" : "secondary"}>{done ? "Concluída" : item.available ? "Disponível" : "Aguardando liberação"}</Badge></div><Button type="button" size="sm" variant={item.available ? "outline" : "ghost"} disabled={!item.available || startLesson.isPending} onClick={() => openLesson(item)}>{item.available ? <Play className="mr-1 h-3.5 w-3.5" /> : <Lock className="mr-1 h-3.5 w-3.5" />}{done ? "Revisar" : item.available ? "Abrir" : "Aguardando"}</Button></div></div>; }) : <p className="rounded-xl bg-muted/40 p-5 text-sm text-muted-foreground">Aulas em preparação pela liderança.</p>}</CardContent></Card>}
    <Dialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)}><AdaptiveFormDialogContent className="sm:max-w-2xl"><div className={adaptiveFormDialogHeaderClassName}><DialogHeader><DialogTitle className="font-display text-[#1e3a5f]">{selected?.lesson.title}</DialogTitle></DialogHeader><p className="mt-1 text-sm text-muted-foreground">Esta etapa é estudo digital; depois haverá uma revisão presencial com o professor.</p></div><AdaptiveFormDialogBody className="space-y-4">{selected?.lesson.summary ? <div className="rounded-xl border border-[#c9a84c]/25 bg-[#fdfaf1] p-4"><Label>Objetivo da aula</Label><p className="mt-1 text-sm leading-6 text-[#1e3a5f]">{selected.lesson.summary}</p></div> : null}<div className="rounded-xl border border-border bg-background p-4"><p className="whitespace-pre-line text-sm leading-7 text-slate-700">{selected?.lesson.content || "O professor ainda está preparando o roteiro desta aula."}</p></div><div className="space-y-2 rounded-xl border border-[#c9a84c]/25 bg-[#fdfaf1] p-4"><Label htmlFor="leadership-reflection">Minha reflexão</Label><p className="text-xs text-muted-foreground">O que você aprendeu e como pretende aplicar?</p><Textarea id="leadership-reflection" value={reflection} onChange={(event) => setReflection(event.target.value)} rows={5} maxLength={4000} placeholder="Escreva sua reflexão..." /></div></AdaptiveFormDialogBody><AdaptiveFormDialogFooter><Button type="button" variant="outline" onClick={() => setSelected(null)}>Sair da aula</Button><Button type="button" className="bg-[#1e3a5f] text-white" disabled={!selected || completeLesson.isPending} onClick={() => selected && path && completeLesson.mutate({ churchId, enrollmentId: path.enrollment.id, lessonId: selected.lesson.id, reflection: reflection || null })}><Save className="mr-2 h-4 w-4" />{completeLesson.isPending ? "Salvando…" : selected?.progress?.status === "concluida" ? "Salvar reflexão" : "Concluir aula"}</Button></AdaptiveFormDialogFooter></AdaptiveFormDialogContent></Dialog>
  </div>;
}

export {};
